### PR TITLE
Notebook for running APP2 and results analysis

### PR DESCRIPTION
**Pull request by fxu10**
The notebook details the installation process for Vaa3D, the python wrapper necessary to run Vaa3D, file I/O related to Vaa3D, as well as results visualizations in Napari. A subsequent results discussions section is also included to detail where the algorithm succeeded and failed. A separate source image folder under /docs/experiments/vaa3d_app2/ is also included for napari screenshots as .png files, which are linked and displayed in the notebook.

### CODE REVIEW

**Review by tathey1 — CHANGES_REQUESTED** [review]
- put your notebook in docs/experiments/vaa3d_app2
- when i download vaa3d for Mac, there's no start_vaa3d.sh file. Instead, there's a vaa3d64.app file. Has this been done on a Mac?
- Can you please add ssd() to brainlit's swc.py file? And then write tests/documentation etc.

Overall, really nice notebook.

**Comment by fxu10** [comment]
> * put your notebook in docs/experiments/vaa3d_app2

> * when i download vaa3d for Mac, there's no start_vaa3d.sh file. Instead, there's a vaa3d64.app file. Has this been done on a Mac?

I haven't tried it on Mac but I'll add a note about a .app file. I'll also it to the new directory asap.

> * Can you please add ssd() to brainlit's swc.py file? And then write tests/documentation etc.

Sure I'll start investigating that.

**Comment by fxu10** [comment]
@tathey1 I implemented the changes:
- Moved the notebook to be under /docs/experiments/vaa3d_app2/
- Added the SSD function to swc.py
- Wrote unit tests for checking valid inputs for as well as numerical outputs of SSD in test_swc.py 
- Removed the SSD function from the notebook, instead imported from brainlit.utils.swc

**Review by tathey1 — COMMENTED** [review]
Looks good, please open this PR [here](https://github.com/neurodata/brainlit) and make sure tests pass, then close this one and you should be good.

**Comment by fxu10** [comment]
Moved pull request to neurodata/brainlit/pulls

**Pull request closed without merging**
